### ISSUE TITLE
Functions.ms is missing

### ISSUE THREAD

**Issue by johanboekhoven** [LPassManager/LPM_3DS_MAX#2]
In the include file it's missing and by bypassing it Treeview.ms can't use "LPM_Fun" as it's undefined.
This renders the current build completely broken! 
Are there any plans to seriously support LPassManager?

**Comment by LPassManager** [comment]
Ill take a look at this tonight

**Comment by LPassManager** [comment]
Hey Johan,
I check the latest build and I didnt see any such issues, are you sure you fully uninstalled the old build before installing this one?  Make you sure have removed any macroscripts from old builds.  
If that doesnt work for you we can setup a teamviewer session where I can try to diagnose it for you.

**Comment by LPassManager** [comment]
Nevermind I think I see the issue!

**Comment by LPassManager** [comment]
Apologies, someone deleted that function when they were testing GITHUB.
Should be all good now, Ive reverted their commit.

**Comment by johanboekhoven** [comment]
Thanks, all is good!

**Comment by johanboekhoven** [comment]
Can we get in contact somehow, I have a few questions?

**Comment by LPassManager** [comment]
Sure thing! Lukashi at gmail dot com
